<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Verify 2FA</title>
    <link rel="stylesheet" href="{{ asset('css/auth/2fa-verify.css') }}">
    <link rel="icon" type="image/png" href="{{ asset('YOKAMOS.png') }}">
</head>
<body>
    
<div class="loginPage">
    <div class="ContentForm">
    <form method="POST" action="{{ route('2fa.check') }}" class="formLogin">
    @csrf
    <h1>Verify 2FA</h1>
    <p>Enter the code from your authentication app</p>
    <div class="inputbox">
        <input type="text" name="code" placeholder="Enter 6-digit code" required>
    </div>
    <button type="submit" class="btn-Login">Verify</button>
</form>

        <div class="imgForm">
            <div class="welcome-section">
                <div class="welcome-subtitle">Secure Authentication</div>
                <p class="welcome-description">
                    Please enter the 6-digit code generated by your authentication app.
                </p>
            </div>
        </div>
    </div>
</div>


</body>
</html>